"""update last

Revision ID: 05837fd9bb64
Revises: 2d6dd78ada7c
Create Date: 2023-06-25 22:57:24.288362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05837fd9bb64'
down_revision = '2d6dd78ada7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
